### ISSUE TITLE
Web UI / Animation Controller

### ISSUE THREAD

**Issue by hansinator** [xHain-hackspace/xDodecahedron#1]
At the CCC Camp 2019 you had a laptop running some web UI to control the dodecahedron animations but unfortunately I can't find it in this repository. I really liked the configurable animations. Is it possible to release the software somehow?

**Comment by Reimerei** [comment]
The software has been released for while, and progressed quiet a bit since congress.
Here is firmware for the ESP32: https://github.com/xHain-hackspace/tr33
And here the web UI control software (run on Pi or Laptop): https://github.com/xHain-hackspace/tr33_control
